FROM node:lts-alpine3.20 AS build

WORKDIR /app

COPY package*.json .
COPY tsconfig.json .
COPY pnpm-workspace.yaml .
COPY turbo.json .
COPY pnpm-lock.yaml .
COPY apps/api ./apps/api


RUN npm install -g pnpm && pnpm install --filter api

COPY . .

RUN pnpm build --filter api

EXPOSE 4000

CMD ["pnpm", "start", "--filter", "api"]
